MSG_USER_INPUT = "Enter the number in centimeters (only digits allowed):"
MSG_NOT_NUMERIC_INPUT = "You have entered not a number. Try again."
MSG_USER_INPUT_NUMBERS = "Enter numbers separated by spaces (only digits allowed):"
MSG_USER_INPUT_MORTGAGE = "Enter your total mortgage amount (only digits allowed):"
MSG_USER_INPUT_INCOME = "Enter your monthly income (only digits allowed):"
